version: '3.7'

services:
  titi:
    image: mysql:8.0
    restart: always
    command: --lower_case_table_names=1
    container_name: mysql-local
    environment:
    - MYSQL_DATABASE=titi
    - MYSQL_ROOT_PASSWORD=1234
    ports:
    - "3306:3306"
    volumes:
    - "./sql/titi.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./sql/titi_data.sql:/docker-entrypoint-initdb.d/2.sql"
    platform: linux/x86_64
